# Generated by Django 6.0.1 on 2026-01-22 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MafiaRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('max_players', models.IntegerField(default=20)),
                ('game_started', models.BooleanField(default=False)),
                ('phase', models.CharField(default='lobby', max_length=20)),
                ('day_number', models.IntegerField(default=0)),
                ('night_number', models.IntegerField(default=0)),
                ('turn_role', models.CharField(blank=True, default='', max_length=20)),
                ('action_deadline', models.DateTimeField(blank=True, null=True)),
                ('vote_stage', models.CharField(choices=[('none', 'none'), ('change_host_yesno', 'change_host_yesno'), ('change_host_pick', 'change_host_pick')], default='none', max_length=20)),
                ('vote_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mafia_host_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MafiaChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='mafia_app.mafiaroom')),
            ],
        ),
        migrations.CreateModel(
            name='MafiaPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('is_host', models.BooleanField(default=False)),
                ('role', models.CharField(default='civil', max_length=20)),
                ('night_target_id', models.IntegerField(blank=True, null=True)),
                ('night_done', models.BooleanField(default=False)),
                ('used_change_host_vote', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='mafia_app.mafiaroom')),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MafiaNightAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night_number', models.IntegerField(default=1)),
                ('action_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mafia_actions_actor', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mafia_actions_target', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night_actions', to='mafia_app.mafiaroom')),
            ],
            options={
                'unique_together': {('room', 'night_number', 'actor', 'action_type')},
            },
        ),
        migrations.CreateModel(
            name='ChangeHostYesNoVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia_app.mafiaroom')),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChangeHostPickVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_as_host_votes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafia_app.mafiaroom')),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
    ]
