# Generated by Django 6.0.1 on 2026-01-25 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mafiaroom',
            name='day_vote_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MafiaDayVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_votes', to='mafia_app.mafiaroom')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mafia_day_votes_target', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mafia_day_votes_voter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room', 'day_number', 'voter')},
            },
        ),
    ]
