# Generated by Django 6.0.1 on 2026-01-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0002_mafiaroom_day_vote_deadline_mafiadayvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='mafiaroom',
            name='winner_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
