# Generated by Django 6.0.1 on 2026-01-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0003_mafiaroom_winner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mafiaroom',
            name='blocked_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
