# Generated by Django 6.0.1 on 2026-01-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0004_mafiaroom_blocked_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mafiaplayer',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
