# Generated by Django 5.2.8 on 2026-02-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_forum_school_app', '0002_article_forumpost_forumcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название темы')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug для URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пост форума', 'verbose_name_plural': 'Посты форума'},
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=3500),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='description',
            field=models.TextField(max_length=3500),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(max_length=24),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='black_forum_school_app.topic', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='black_forum_school_app.topic', verbose_name='Тема'),
        ),
    ]
