# Generated by Django 5.2.8 on 2026-02-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_forum_school_app', '0003_topic_alter_article_options_alter_forumpost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={},
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='black_forum_school_app.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to='black_forum_school_app.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
