# Generated by Django 5.2.8 on 2026-02-13 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_forum_school_app', '0004_alter_forumpost_options_alter_article_topic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='topic',
        ),
        migrations.AddField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='articles', to='black_forum_school_app.topic', verbose_name='Темы'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='forum_posts', to='black_forum_school_app.topic', verbose_name='Темы'),
        ),
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(default='primary', help_text='Bootstrap цвет: primary, success, danger, warning, info', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(blank=True, help_text='Класс иконки (например, bi-game, bi-book)', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
