# Generated by Django 5.2.8 on 2026-02-20 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_forum_school_app', '0006_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_questions', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
