# Generated by Django 6.0.1 on 2026-05-15 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_forum_school_app', '0008_emaildigest_emailcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcode',
            name='user',
        ),
        migrations.AddField(
            model_name='emailcode',
            name='email',
            field=models.EmailField(default='none@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
