# Generated by Django 5.2.8 on 2026-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_forum_school_app', '0009_remove_emailcode_user_emailcode_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcode',
            name='code_type',
            field=models.CharField(default='login', max_length=20),
        ),
    ]
